"""
Copyright 2019 Pacific Gas and Electric Company

ALL RIGHTS RESERVED
"""
import logging
import os
import sys
from typing import List, Union

from stix2 import NetworkTraffic, properties, CustomExtension


@CustomExtension(NetworkTraffic, 'x-dnp3-header', [
    ('addr', properties.IntegerProperty()),
    ('al_2bit', properties.IntegerProperty()),
    ('al_aiq_b0', properties.BooleanProperty()),
    ('al_aiq_b1', properties.BooleanProperty()),
    ('al_aiq_b2', properties.BooleanProperty()),
    ('al_aiq_b3', properties.BooleanProperty()),
    ('al_aiq_b4', properties.BooleanProperty()),
    ('al_aiq_b5', properties.BooleanProperty()),
    ('al_aiq_b6', properties.BooleanProperty()),
    ('al_aiq_b7', properties.BooleanProperty()),
    ('al_ana', properties.IntegerProperty()),
    ('al_ana_double', properties.FloatProperty()),
    ('al_ana_float', properties.FloatProperty()),
    ('al_ana_int', properties.IntegerProperty()),
    ('al_anaout', properties.IntegerProperty()),
    ('al_anaout_double', properties.FloatProperty()),
    ('al_anaout_float', properties.FloatProperty()),
    ('al_anaout_int', properties.IntegerProperty()),
    ('al_aoq_b0', properties.BooleanProperty()),
    ('al_aoq_b1', properties.BooleanProperty()),
    ('al_aoq_b2', properties.BooleanProperty()),
    ('al_aoq_b3', properties.BooleanProperty()),
    ('al_aoq_b4', properties.BooleanProperty()),
    ('al_aoq_b5', properties.BooleanProperty()),
    ('al_aoq_b6', properties.BooleanProperty()),
    ('al_aoq_b7', properties.BooleanProperty()),
    ('al_biq_b0', properties.BooleanProperty()),
    ('al_biq_b1', properties.BooleanProperty()),
    ('al_biq_b2', properties.BooleanProperty()),
    ('al_biq_b3', properties.BooleanProperty()),
    ('al_biq_b4', properties.BooleanProperty()),
    ('al_biq_b5', properties.BooleanProperty()),
    ('al_biq_b6', properties.BooleanProperty()),
    ('al_biq_b7', properties.BooleanProperty()),
    ('al_bit', properties.BooleanProperty()),
    ('al_bocs', properties.BooleanProperty()),
    ('al_boq_b0', properties.BooleanProperty()),
    ('al_boq_b1', properties.BooleanProperty()),
    ('al_boq_b2', properties.BooleanProperty()),
    ('al_boq_b3', properties.BooleanProperty()),
    ('al_boq_b4', properties.BooleanProperty()),
    ('al_boq_b5', properties.BooleanProperty()),
    ('al_boq_b6', properties.BooleanProperty()),
    ('al_boq_b7', properties.BooleanProperty()),
    ('al_cnt', properties.IntegerProperty()),
    ('al_con', properties.BooleanProperty()),
    ('al_count', properties.IntegerProperty()),
    ('al_ctl', properties.IntegerProperty()),
    ('al_ctrlstatus', properties.IntegerProperty()),
    ('al_ctrq_b0', properties.BooleanProperty()),
    ('al_ctrq_b1', properties.BooleanProperty()),
    ('al_ctrq_b2', properties.BooleanProperty()),
    ('al_ctrq_b3', properties.BooleanProperty()),
    ('al_ctrq_b4', properties.BooleanProperty()),
    ('al_ctrq_b5', properties.BooleanProperty()),
    ('al_ctrq_b6', properties.BooleanProperty()),
    ('al_ctrq_b7', properties.BooleanProperty()),
    ('al_da_double', properties.FloatProperty()),
    ('al_da_float', properties.FloatProperty()),
    ('al_da_int16', properties.IntegerProperty()),
    ('al_da_int32', properties.IntegerProperty()),
    ('al_da_int8', properties.IntegerProperty()),
    ('al_da_length', properties.IntegerProperty()),
    ('al_da_uint16', properties.IntegerProperty()),
    ('al_da_uint32', properties.IntegerProperty()),
    ('al_da_uint8', properties.IntegerProperty()),
    ('al_da_value', properties.StringProperty()),
    ('al_datatype', properties.IntegerProperty()),
    ('al_file_auth', properties.IntegerProperty()),
    ('al_file_blocknum', properties.IntegerProperty()),
    ('al_file_data', properties.StringProperty()),
    ('al_file_handle', properties.IntegerProperty()),
    ('al_file_lastblock', properties.BooleanProperty()),
    ('al_file_maxblock', properties.IntegerProperty()),
    ('al_file_mode', properties.IntegerProperty()),
    ('al_file_perms', properties.IntegerProperty()),
    ('al_file_perms_exec_group', properties.BooleanProperty()),
    ('al_file_perms_exec_owner', properties.BooleanProperty()),
    ('al_file_perms_exec_world', properties.BooleanProperty()),
    ('al_file_perms_read_group', properties.BooleanProperty()),
    ('al_file_perms_read_owner', properties.BooleanProperty()),
    ('al_file_perms_read_world', properties.BooleanProperty()),
    ('al_file_perms_write_group', properties.BooleanProperty()),
    ('al_file_perms_write_owner', properties.BooleanProperty()),
    ('al_file_perms_write_world', properties.BooleanProperty()),
    ('al_file_reqID', properties.IntegerProperty()),
    ('al_file_size', properties.IntegerProperty()),
    ('al_file_status', properties.IntegerProperty()),
    ('al_file_name', properties.StringProperty()),
    ('al_file_string_length', properties.IntegerProperty()),
    ('al_file_string_offset', properties.IntegerProperty()),
    ('al_fin', properties.BooleanProperty()),
    ('al_fir', properties.BooleanProperty()),
    ('al_frag_data', properties.StringProperty()),
    ('al_fragment', properties.IntegerProperty()),
    ('al_fragment_count', properties.IntegerProperty()),
    ('al_fragment_error', properties.IntegerProperty()),
    ('al_fragment_multipletails', properties.BooleanProperty()),
    ('al_fragment_overlap', properties.BooleanProperty()),
    ('al_fragment_overlap_conflict', properties.BooleanProperty()),
    ('al_fragment_reassembled_length', properties.IntegerProperty()),
    ('al_fragment_reassembled_in', properties.IntegerProperty()),
    ('al_fragment_toolongfragment', properties.BooleanProperty()),
    ('al_fragments', properties.StringProperty()),
    ('al_func', properties.IntegerProperty()),
    ('al_iin', properties.IntegerProperty()),
    ('al_iin_bmsg', properties.BooleanProperty()),
    ('al_iin_cc', properties.BooleanProperty()),
    ('al_iin_cls1d', properties.BooleanProperty()),
    ('al_iin_cls2d', properties.BooleanProperty()),
    ('al_iin_cls3d', properties.BooleanProperty()),
    ('al_iin_dol', properties.BooleanProperty()),
    ('al_iin_dt', properties.BooleanProperty()),
    ('al_iin_ebo', properties.BooleanProperty()),
    ('al_iin_fcni', properties.BooleanProperty()),
    ('al_iin_oae', properties.BooleanProperty()),
    ('al_iin_obju', properties.BooleanProperty()),
    ('al_iin_pioor', properties.BooleanProperty()),
    ('al_iin_rst', properties.BooleanProperty()),
    ('al_iin_tsr', properties.BooleanProperty()),
    ('al_index', properties.IntegerProperty()),
    ('al_obj', properties.IntegerProperty()),
    ('al_objq_code', properties.IntegerProperty()),
    ('al_objq_index', properties.IntegerProperty()),
    ('al_objq_prefix', properties.IntegerProperty()),
    ('al_objq_range', properties.IntegerProperty()),
    ('al_octet_string', properties.IntegerProperty()),
    ('al_off_time', properties.IntegerProperty()),
    ('al_on_time', properties.IntegerProperty()),
    ('al_point_index', properties.IntegerProperty()),
    ('al_ptnum', properties.IntegerProperty()),
    ('al_range_abs', properties.IntegerProperty()),
    ('al_range_quantity', properties.IntegerProperty()),
    ('al_range_start', properties.IntegerProperty()),
    ('al_range_stop', properties.IntegerProperty()),
    ('al_reltimestamp', properties.IntegerProperty()),
    ('al_seq', properties.IntegerProperty()),
    ('al_size', properties.IntegerProperty()),
    ('al_time_delay', properties.IntegerProperty()),
    ('al_timestamp', properties.StringProperty()),
    ('al_unknown_data_chunk', properties.StringProperty()),
    ('al_uns', properties.BooleanProperty()),
    ('buffering_user_data_until_final_frame_is_received', properties.StringProperty()),
    ('ctl', properties.IntegerProperty()),
    ('ctl_clr', properties.IntegerProperty()),
    ('ctl_dfc', properties.BooleanProperty()),
    ('ctl_dir', properties.BooleanProperty()),
    ('ctl_fcb', properties.BooleanProperty()),
    ('ctl_fcv', properties.BooleanProperty()),
    ('ctl_op', properties.IntegerProperty()),
    ('ctl_prifunc', properties.IntegerProperty()),
    ('ctl_prm', properties.BooleanProperty()),
    ('ctl_secfunc', properties.IntegerProperty()),
    ('ctl_trip', properties.IntegerProperty()),
    ('dnp_data_chunk', properties.StringProperty()),
    ('dnp_data_chunk_len', properties.IntegerProperty()),
    ('dnp_data_chunk_crc', properties.IntegerProperty()),
    ('dnp_data_chunk_crc_status', properties.IntegerProperty()),
    ('data_chunk_CRC_incorrect', properties.StringProperty()),
    ('dnp_hdr_crc_status', properties.IntegerProperty()),
    ('dst', properties.IntegerProperty()),
    ('empty_field_limit', properties.StringProperty()),
    ('hdr_crc', properties.StringProperty()),
    ('hdr_CRC_incorrect', properties.StringProperty()),
    ('hdr_CRC_bad', properties.BooleanProperty()),
    ('iin_abnormal', properties.StringProperty()),
    ('invalid_length', properties.StringProperty()),
    ('len', properties.IntegerProperty()),
    ('level', properties.IntegerProperty()),
    ('num_items_invalid', properties.StringProperty()),
    ('num_items_neg', properties.StringProperty()),
    ('src', properties.IntegerProperty()),
    ('start', properties.IntegerProperty()),
    ('tr_ctl', properties.IntegerProperty()),
    ('tr_fin', properties.BooleanProperty()),
    ('tr_fir', properties.BooleanProperty()),
    ('tr_seq', properties.IntegerProperty()),
    ('unknown_group0_variation', properties.StringProperty()),
    ('unknown_object', properties.StringProperty())
])
class DNP3Header:
    pass


DNP3Types = List[Union[DNP3Header]]

if __name__ == '__main__':
    from packetengine import FilteringFileCapture
    from dnp3_decoder import DNP3Decoder
    if len(sys.argv) == 1:
        print(f"{__file__} Error: Supply a pcap file as an argument")
        sys.exit(1)
    pcap_file = sys.argv[1]
    logging.debug("Pcap file is: %s", pcap_file)
    stats = os.stat(pcap_file)
    capture = FilteringFileCapture(pcap_file, "port 20000")
    count = 1
    dnp3decoder = DNP3Decoder()
    all_observed = []
    objects = []
    for pkt in capture:
        objects = dnp3decoder.decoder(pkt)

    for o in objects:
        print(str(o))
